module.exports = {
  name: 'blague',
  description: 'Blague du grand wsassi',
  aliases: [],
  usage: '[nom d\'utilisateur]',
  cooldown: 10,
  execute(msg, args, server) {
    lol = [
      "Pourquoi David Bowie, Prince et Frank Sinatra sont-ils morts en l’espace de quelques mois ? Parce que Dieu a découvert le Cloud.",
      "Quelle est la solution de l’équation e^x = segara ? Ln segara.",
      "Pourquoi une solution ne vous calcule jamais quand vous lui parlez ? Elle est trop concentrée.",
      "Pourquoi il faut toujours miser sur les numéros 2, 3, 5, 7, 11 au PMU ? Parce qu’ils sont toujours premiers.",
      "Qui est le plus impacté par l’interdiction de la bigamie ? L’oxygène : il a deux liaisons covalentes.",
      "Pourquoi la fonction f(x) = x²+ 1 est toujours positive ? Parce qu’elle a un large sourire.",
      "Deux personnes discutent à l’arrêt de bus : « Punaise, ce gars, il démarre au π/2 ‼ ».",
      "Est-ce que donner à manger de l’Uranium 235 à un oiseau, c’est lui faire la Becquerel ? ",
      "Qu’est-ce qu’un Pi (π) insomniaque ? Un pissenlit.",
      "Le QI d’une personne, c’est comme la fonction racine carrée : un QI négatif est impossible mais on apprend plus tard que dans certains cas, ça peut exister.",
      "Les couples : au début, c’est un Bezout puis ça finit toujours avec un Gauss.",
      "Si une bobine s’inscrivait à la Nouvelle Star, quelle chanson chanterait-elle ? Daniel Balavoine : le Chanteur.",
      "Pourquoi e2iπ est-il un mauvais avocat ? Car il n’a que des arguments nuls. ",
      "Pourquoi les nombres réels sont-ils tordus ? Parce qu’ils ne sont pas droits comme un i. ",
      "Quel est l’organe humain le plus fort en maths ? Les reins.",
      "Que dit un 0 quand il voit un 8 ? « Quelle belle ceinture ! ».",
      "Dans quel cinéma un physicien a-t-il l’habitude de regarder un film ? Au cinéma Tique.",
      "Que mettent les coordonnées d’un point du repère quand ils se caillent trop (en hiver) ? Ils mettent une polaire.",
      "Quel est le segment le plus vieux dans un repère ? Le segment [AG].",
      "Comment les atomes font-ils pour voir s’il va y avoir des bouchons dans la matière ? Ils regardent le Boson Futé.",
      "Quel serait le comble de la fonction cosinus ? D’avoir une sinusite.",
      "Qu’est-ce qu’un nuage complexe ? Un iCloud. ",
      "Qu’est ce que 3.14 coloscopes ? Une coloscopie.",
      "Quel type de foulard un vecteur porte-t-il ? Un Chasles. ",
      "Deux dioptres jouent au poker : « Alors t’as des cartes ? »",
      "Quel est le plat favori des télescopes ? Les lentilles.",
      "Quel genre de musique le Fer, le Cuivre et le plomb adorent-ils ? Le métal.",
      "Quelle est la musique préférée des nombres relatifs ? Le Lac des Signes.",
      "Une calculette bon marché et un nombre complexe discutent. Le nombre complexe : « Pourquoi tu ne me calcules jamais ?! Je suis là quoi ‼ ».",
      "C’est un couple de fonctions qui sont… assez carrés. En voyant leur fiston, Nome, assez turbulent, les parents lui disent : « Oooh, sois poli, Nome ! ».",
      "Quelle est la fonction la plus confortable/douillette ? Cos(y). ",
      "Un chimiste n’est jamais surpris : il cétonne.",
      "Deux électrons sur le Titanic. Lorsqu’ils apprennent le naufrage imminent de leur navire, ils se mettent à crier « AAAAAH !!! Nous Coulomb !!! »",
      "Quelle est la marque préférée de tablettes pour les fonctions mathématiques ? Arccos(x).",
      "Quelle est la droite la plus triste de l’espace (O, x, y, z) ? La droite (D’). ",
      "Que fait une application pour planer ? Il se fait une injection.",
      "Quel est le comble d’un vecteur ? De ne pas être conforme aux normes. ",
      "Pourquoi la fonction cosinus est têtue comme une mule ? Parce qu’elle est bornée.",
      "Que fait Newton lorsqu’il va à The Voice ? Il fait un champ Newtonien.",
      "Pourquoi Ité est toujours pardonné quelque soit ses bêtises ? Parce que « Ce n’est pas grave, Ité ! ».",
      "On parle toujours de torseurs. Mais où sont leurs torfrères ?",
      "Comment une famille de vecteurs fait-elle pour avoir des enfants ? Elle utilise le théorème de la base incomplète.",
      "Qu’est-ce qu’un iPhone ? Un téléphone complexe. ",
      "Quel est le comble pour une matrice triangulaire inférieure ? Avoir un complexe d’infériorité.",
      "Quelle est la matrice la plus laide ? La matrice identité I2. ",
      "Quel était le type le plus stressée au monde ? Pascal : il avait la pression !",
      "Quel est le nombre qui est le plus fort à cache-cache ? La constante de Planck.",
      "Comment fait-on pour trouver un schéma de logique combinatoire en NOR ? Avec une boussole.",
      "Pourquoi un donut n’a jamais raison ? Parce qu’il a tore.",
      "Un facteur de qualité est un type qui te donne de bonnes lettres.",
      "Si un torseur participait à la Nouvelle Star, que chanterait-il ? Un champ vectoriel.",
      "Quel est le signal qui sait le mieux se garer ? Le signal en créneau.",
      "Si un physicien t’amène boire un verre, pourquoi faut-il s’attendre à ce qu’il y ait beaucoup de monde ? Parce qu’il t’amènera dans un bar.",
      "Si un torseur couple doit aller en cours, comment devra-t-il s’habiller ? Avec un uniforme.",
      "« Les vacances sont finies ! Il faut ranger ses vêtements différentiels (d’été )… »",
      "Si un garçon a réussi à passer son permis, comment pourrait-il être appelé ? Un conducteur ohmique. ",
      "Quel est le comble pour un scientifique ? De mater Mathique et que cette dernière ne le calcule même pas.",
      "Un mathématicien ne s’éclaire pas avec une lampe mais avec un projecteur orthogonal.",
      "Quelle est la fonction la plus perdue ? La fonction logarithme népérien : car ln s’égara.",
      "Un solénoïde ne respire pas : il N spire et il x spire. ",
      "Quel est l’espace vectoriel le plus explosif ? C’est l’espace vectoriel ℂ4.",
      "Quel est le vêtement privilégié de i ? Le corset.",
      "Pourquoi une poire est un fruit injectif ? Parce que son noyau est nul.",
      "La meilleure déclaration d’amour : « Je te rapport de transformation ».",
      "« L’électrostatique, c’est un truc de Gauss ! »",
      "Un polymère , c‘est une maman qui a de bonnes manières.",
      "Quelle est la liaison en SI qui n’est jamais en retard ? La liaison ponctuelle.",
      "Une électrode, quand elle suit les dernières tendances vestimentaires, elle n’est pas à la mode mais à l’anode.",
      "Ce sont deux lames de fer qui voient passer une lame de cuivre. Alors la première lame dit à son acolyte : « tu ne trouves pas qu’elle a un beau Cu ? ».",
      "Qu’est-ce qu’une salle de classe avec 29 PSI ? Une classe à 2 bars.",
      "Les séries, quand elles rigolent, elles ont un Fourier.",
      "« Riemann et les Laplaciens Crétins ».",
      "Quelle est la chanson d’Indila qui convient le mieux aux moteurs ? « Tourner dans le vide ».",
      "Et sinon, qu’est-ce qu’un moteur qui ne fournit aucun effort ? C’est un moteur célibataire.",
      "Quels sont les théorèmes les plus explosifs en sciences de l’ingénieur ? Les théorèmes généraux de la dynamite.",
      "Quelle est le système le plus chaud à résoudre ? Le système de Cramer.",
      "En chimie, quelle est la représentation la plus… hot ? La représentation de Cram.",
      "Un archer, lorsqu’il fuit, ne prend pas la tangente : il prend l’arc tangente.",
      "Un système asservi ne voyage pas : il va voir du PI.",
      "Pourquoi un mathématicien imprime-t-il ses photos à moitié ? Parce qu’il fait un développement limité.",
      "Un repère ne s’ennuie pas : il tourne en ROND.",
      "Pourquoi un mathématicien a-t-il toujours des techniciens de surface avec lui ? Pour pouvoir trouver les espaces propres plus facilement.",
      "Pourquoi est-il difficile de faire de l’humour avec un opérateur différentiel ? Parce qu’il prendra au sérieux toute remarque au second degré.",
      "Quel est l’instrument de musique de prédilection des fonctions périodiques ? L’harmonica.",
      "Quelle est la matrice qui n’aura pas droit à des cadeaux pour Noël ? La matrice de passage.",
      "Que fait un éléphant impuissant ? Il barrit sans trique.",
      "Que dit un mathématicien quand il se noie ? Log log log…",
      "Qu’est-ce qu’un chauffeur qui conduit mal ? Un isolant.",
      "Quelle est la personne qui a le plus de ressources ? C’est Nernst : parce qu’il a du potentiel.",
      "Que met une aile d’avion quand elle a froid ? Une polaire.",
      "On parle de réduction de matrices. Mais pourquoi on ne parle jamais d’oxydation de matrices ?",
      "Je voudrais appeler mon lapin Faraday. Comme ça, il sera dans une cage de Faraday.",
      "Quel est le point commun entre les bébés et l’argon ? Leurs couches sont toujours pleines.  ",
      "Quel est l’espace vectoriel préféré des charcutiers ? Le SO(6).",
      "Un jour, j’ai voulu faire une blague bidon à une bouteille d’hélium. Elle n’a même pas réagi …",
      "Les aquariums ont aussi leur code civil : les occupants doivent obéir à la loi de Poisson.",
      "Pourquoi un jardinier est-il un bon mécanicien ? Parce qu’il a plein d’arbres moteurs.",
      "Les formules en optique, c’est compliqué… Y’a pas photon !",
      "Si une personne se brûle au troisième degré et dérive sa brûlure , est-ce que ça devient une brûlure du second degré ?",
      "« Les schémas équivalents en élec, c’est pas ma tasse de Thévenin ! »",
      "M. et Mme Fait ont un fils. Comment s’appelle-t-il ? Gaspard.",
      "Si Clara Morgane rayonne, fera-t-elle des rayons X ?",
      "Quel est l’hymne préféré des équas différentielles ? L’ODE à la joie.",
      "Que se passe-t-il lorsqu’on dérive une sinusite ? On obtient une cosinusite.",
      "Qu’est-ce qu’un filtre en colère ? Un filtre Wiener. ",
      "Il y a 10 sortes de gens dans le monde : ceux qui comprennent le binaire et ceux qui ne le comprennent pas.",
      "Quel est le groupe sanguin d’un geek ? C++.",
      "Quel navigateur Internet un cuisinier utilise-t-il ? Mozzarella Firefox.",
      "Vous croyez que si on pêche une raie et puis qu’on la plonge dans un seau de peinture bleue, ça deviendra un blu-ray ?",
      "Pourquoi un pirate informatique aime-t-il son travail ? Parce que ça lui tient hacker.",
      "Qu’y a-t-il au pied d’un arc-en-ciel ? Un Nyan Cat qui s’est écrasé au sol.",
      "Deux ordinateurs discutent. L’un d’eux dit : « Mec, j’ai mal au DOS … »",
      "Pourquoi les flaques d’eau ont une bonne qualité sonore? T’as déjà vu une MP3 d’eau ?",
      "Pourquoi est-ce une bonne idée de lancer le CD de Windows Vista comme un frisbee à son chien ? Parce qu’un chien aime les OS…",
      "Qu’est-ce qu’un DVD mort ? Un DVD-Rip.",
      "Quel est le registre littéraire du code source de Windows? Regedit.",
      "Ce sont deux logiciels qui sont en train de s’installer. L’un deux s’installe sur le D:\. Du coup, l’autre logiciel lui dit : « Allez, viens danser ! ».",
      "Quelle est la boisson la plus alcoolisée selon un geek ? Alcohol 120%.",
      "Qu'est-ce qu'un torrent téléchargé par Hitler? Un génoseed.",
      "Un geek n’achète pas de canapé convertible mais un canapé qwertyble.",
      "En été, quelle est la touche la plus utilisée ? F5 puisqu’elle rafraichit (la page).",
      "Qui est le meilleur programmeur de batch ? Batman.",
      "Un chien programmeur ne cherche pas d’os : il compile son propre os.",
      "Si Dom Juan était un ordi, que maitriserait-il le plus ? Le drag and drop. ",
      "Un programmeur ne prend pas de vitamine C, il prend de la vitamine C++.",
      "Comment un terminal Linux fait-il pour aller quelque part ? Il se met en root.",
      "Lorsqu’il mange, sur quoi un geek mange-t-il ? Sur une nappe IDE.",
      "Que faut-il donner à un navigateur Internet quand il a faim ? Des cookies.",
      "Que met un programme comme sous-vêtements? Il met des <string.h>.",
      "Un geek n’est jamais lassé par quoi que ce soit : c’est juste que ça le fichier.",
      "Jick et Jack, 2 paires d’écouteurs sont en train de braquer une banque (original !). En voyant la faible réactivité de son acolyte, Jick s’écrie alors : « Mais qu’est-ce que tu fiches, Jack ?! ».",
      "Quel est le type de téléphone favori des nudistes ? Les téléphones nus.",
      "Un geek, au petit déj, il mange des serials, fume du crack pour être dans les clouds mais comme ce n’est pas bon pour la santé il met des patchs pour arrêter de fumer.",
      "Sur quoi un ingénieur se repose-t-il? Sur un Matlab.",
      "Qu’est-ce qu’un T-Shirt Nike dans la mer ? Une valeur à virgule flottante.",
      "Quel est le logiciel qui faut toujours avoir quand on a un petit creux ? C’est Firefox : il a de si bons cookies !",
      "Quelle est la drogue préférée des signaux numériques ? Le LSB.",
      "Pourquoi un geek peut-il être considéré comme un meurtrier ? Parce qu’il ne fait qu’exécuter ses programmes.",
      "Quelle est la chaîne de montagnes préférée de la mémoire ? La Cordillère des NAND.",
      "Pourquoi un disque dur est souvent diabolique ? Parce qu’il est SATAnique.",
      "Comment Al Gore se reproduit-il ? Il lance Maple et il fait un algorithme.",
      "Pourquoi Staline était-il au courant de toutes les actualités de son pays ? Parce qu’il suivait les fl-URSS.",
      "Un geek azerty en vaut deux.",
      "Que dit une disquette qui est trop pleine ? Rhooh, faut que je perde quelques kilos !",
      "Qu’est-ce qu’une boucle for écrite il y a quelques centaines de lignes ? Une boucle fort fort lointaine.",
      "Que donnent Amazon quand ils font un cadeau ? Ils donnent un Kindle Surprise.",
      "Tu sais pourquoi ML se vend bien ? Parce que tous les sites veulent HTML.",
      "Que fait un voleur d’ordinateurs après son larcin ? Il prend la F8.",
      "Un informaticien peut aussi faire des greffes de cœur : lorsqu’il change de processeur.",
      "Que fait un site Internet quand il vaut voyager ? Il fait ses balises !",
      "Pourquoi les supercalculateurs sont-ils nuls pour raconter des blagues ? Parce qu’ils font beaucoup de flops. ",
      "Salamèche et sa mère sont dans la forêt. Soudain, sa mère lui dit « Arrête de jouer avec le feu ! ».",
      "Deux fœtus dans un ventre : « Eeeh, tu m’as encore donné un coup de pied ! C’est placenta ! ».",
      "Un philosophe ne compte pas mais il Kant.",
      "Un téléphone ne meurt pas : il déclare forfait.",
      "Deux citrons discutent au rayon fruits de Carrefour. L’un d’eux raconte une blague assez marrante (lisez ce recueil, ça ne manque pas !). En vue de la réaction de son copain le premier citron lui demande : « Mais pourquoi tu ris jaune ? »",
      "La carpe a aussi son jour : Carpe diem.",
      "Arrête avec tes Sean Connery !",
      "« Didier des villes et Didier Deschamps ».",
      "Il existe deux types de champs : les bas-champs et les Auchan.",
      "Deux boomerangs discutent. Lorsque l’un annonce le décès de son copain (à cause d’un incendie), l’autre répond : « J’en reviens pas ! ».",
      "Deux glaçons se font photographier. Le photographe : « Dites Freeze ! ».",
      "Deux journaux discutent : « Allez presse-toi ! »",
      "Plusieurs tasses à café sont sur le point de faire un 100 mètres. L’arbitre leur dit : « À vos marcs … »",
      "« Je ne suis pas devin, je suis quarante ! »",
      "Deux chaussures qui partent un week-end : « Allez, à la semelle prochaine ! ».",
      "La mer : le paradis des alcooliques car c’est le seul endroit où il y a un bar tous les dix mètres.",
      "Une tomate, chez un docteur, ne fait pas un check-up mais un ketch-up.",
      "C’est une photo qui va chez le coiffeur. Elle demande : « Bonjour, je voudrais me couper les TIFF ».",
      "Adriana Karembeu, quand elle veut bien s’habiller, elle ne se met pas sur son 31 mais sur 42.",
      "Un arbre, quand il a froid, il ne met pas une écharpe mais une écharde.",
      "Un œuf va dans un frigo avec ses amis et il dit « Je me caille ici ! ».",
      "En fait, un smiley , il rit jaune !",
      "ζζζζζ ζζζζζ ζζζζζ ζζζζζ ζζζζζ ζζζζζ ζζζζζ ζζζζζ ζζζζζ ζζζζζ <-- Les Zêta-Unis.",
      "Une vache ne colorie pas avec des crayons mais avec des trayons.",
      "Einstein, quand il a faim, il ne mange pas à la cantine mais à la quantique.",
      "J’ai appelé mon sèche-cheveux Vection. Comme ça, quand il me brûle, je peux lui dire « T’es con, Vection ! »",
      "Pourquoi les habitantes de Six-Fours ont-elles toujours chaud ? Parce qu’elles sont des Sixfournaises.",
      "En fait, Hotmail, c’est pas une boîte à lettres incendiée ?",
      "Quel est le comble d’une mante religieuse ? D’être athée.",
      "Pourquoi Spiderman est-il bon en peinture ? Parce qu’il sait faire de bonnes toiles.",
      "Pourquoi une feuille de papier n’aime pas se baigner ? Parce qu’elle n’a pas pied.",
      "Que met le Soleil lorsque son pantalon est trop large ? Une Sun Belt.",
      "Si Freddie Mercury avait fait de la boxe, qu’est-ce qu’il serait devenu ? Un guet-apens.",
      "Quel est le comble pour le PDG de Kia ? D’avoir comme téléphone un Nokia.",
      "Quelle est la friandise préférée d’une horloge ? Les Tic-Tac.",
      "Que fait Sacha dans sa baignoire ? Il fait des bulles bizarres.",
      "Pourquoi la Belle au Bois Dormant est-elle née dans la meilleure époque ? Car elle a vécu durant l’Âge d’Or.",
      "T’as 3 poussins et t’en voulais 2. Comment tu fais ? T’en pousses un.",
      "Quel est le comble d’une tablette de chocolat blanc ? D’être vendue au marché noir.",
      "Pourquoi une graine a-t-elle toujours mal à la tête ? Car elle a 2 mi-graines.",
      "Que fait un mur lorsqu’un marteau lui porte trop préjudice ? Il porte plinthe.",
      "Quelle est la voiture la mieux habillée ? La Polo (de Volkswagen).",
      "Quel est le jeu favori d’un ver ? Le solitaire.",
      "Que se passe-t-il quand Batman se prend une balle ? Il fait un home-run.",
      "Selon le fils de Shrek, qu’est-ce que Skrek ? Un pervers. ",
      "Pourquoi peut-on dire que la Ferrari est une écurie ? Parce qu’elle a 300 CV.",
      "Quel serait le comble de la ville de Berlin? Avoir Facebook (et donc un mur). ",
      "Quel serait le comble de Pirates des Caraïbes ? Que Jack Sparrow pirate le film sur Internet.",
      "Avec quoi George W. Bush se lave-t-il ? Avec du bain de bouche. ",
      "Pourquoi est-il déconseillé de mettre des trucs sur une télé (c’est-à-dire la charger, quoi) ? Parce que télécharger , c’est mal ! ",
      "Pourquoi Staline avait une humeur massacrante (bah ouais, il en a tué, des gens) ? Parce qu’il s’est levé du pied communiste.",
      "Comment appelle-t-on la mise à l’écart d’un lézard ? La mise en tarentaine.",
      "Pourquoi les grands-pères en Russie sont-ils aussi vieux ? Car ce sont des papis russes.",
      "Si John Lennon se fait mixer, est-ce que ça va faire du Beetlejuice ? ",
      "Quelles sont les chaussures préférées de la Faucheuse ? Les pompes funèbres.",
      "Pourquoi il fait toujours chaud dans une voiture en été ? Parce qu’il y a un chauffeur.",
      "Pourquoi l’imprimante d’une blonde ne marche jamais et sent la pâtisserie ? Parce qu’elle a mis mille-feuille.",
      "Quel est le point commun entre George W. Bush et New-York City ? Ce sont tous deux des grands ports.",
      "Pourquoi les bananes sont-elles aussi fines ? Car elles font beaucoup de régimes (de bananes) !",
      "Pourquoi un pack de bouteilles reste-t-il immobile ? Parce qu’il y a des bouchons.",
      "Quelle est la lettre la plus matinale ? τ.",
      "Que fait un stylo quand il s’inquiète ? Il se fait un sang d’encre.",
      "Comment appelle-t-on un char qui a bon goût ? Un charbon.",
      "Si quelqu’un met une musique assez nulle mais à fond, est-ce que le volume sonore se quantifie en Décibels ou en Décimoches ? ",
      "Quel est le plat favori du disciple de Socrate ? Les plats (de) Thon.",
      "Quel est le comble pour un plombier ? D’être en manque de tuyaux.",
      "Pourquoi n’est-il pas bon d’être un glaçon ? Parce qu’il a plein de frais.",
      "Pourquoi vendeur de disques est un métier à risques ? Parce qu’ils ont des CD.",
      "Pourquoi dans le film Pinocchio, le héros a-t-il un nez aussi long ? Parce que c’est un film Disney.",
      "Pourquoi les vampires préfèrent sucer le sang des chevaux ? Parce qu’ils ont plus de chance d’avoir du pur sang.",
      "Quel est le comble pour des filles jumelles ? D’être myope.",
      "Que font les lettres de l’alphabet grec lorsqu’elles ne se sentent pas bien dans leur peau ? Elles vont voir le Ψ.",
      "Dans un jeu télévisé, pourquoi les mauvaises réponses sont en général en rouge ? Parce que l’animateur dit « Tapez votre réponse (sur le clavier)».",
      "Quelle marque de sac Abdel Halim aime-t-il le plus ? Les sacs Longchamp.",
      "Que font deux personnes de petite taille quand ils se mettent ensemble ? Ils font une nainfusion.",
      "Quel est le plat cuisiné qui n’est jamais à l’heure ? Le steak Tartare. ",
      "Quelle est la boisson préférée des cahiers ? Le lait caillé.",
      "Quel est le plat le plus froid qui puisse exister ? La gelée.",
      "Quel serait le comble pour une femmelette ? De se marier avec une omelette !",
      "Pourquoi le temps est-elle une notion vraiment sournoise ? Parce qu’elle fait souvent des leurres.",
      "Quel est le jeu dans lequel les martiens excellent-ils ? Les arts martiaux.",
      "Quel est le vêtement le plus triste ? La blouse.",
      "Quels sont les noms qui peuvent provoquer de gros débats ? C’est Paul et Mique.",
      "Qu’est-ce qu’un train qui n’a jamais pris la pluie ? C’est un véhicule intrinsèque.",
      "Qu’est-ce que cinq cents personnes qui n’arrivent pas à avoir pied dans une plage ? Une ramette de papier.",
      "Pourquoi ne faut-il jamais manger un plat qui est en train de faire un film ? Parce que ça tourne.",
      "Quel est la personne la plus âgée ? Pierre : parce qu’il a l’âge de pierre !",
      "Est-ce que l’application Facebook peut être considérée comme une application linéaire ?",
      "Pourquoi une personne qui porte un bonnet respire-t-elle mieux ? Parce qu’elle a deux nez.",
      "Tu crois que les chèques s’appelaient avant des chècoslaves ?",
      "Pourquoi les Sims est le jeu préféré des opérateurs téléphoniques ? Parce qu’ils utilisent beaucoup de cartes SIM.",
      "Que fait un circuit électrique lorsqu’il va à la banque ? Il ouvre un compte courant.",
      "Si une personne parle du mont Everest, est-ce que c’est un haut-parleur ?",
      "Quel est le comble pour un vendeur chez Morgan ? D’avoir une fringale.",
      "Quel est la fée qui fournit les denrées alimentaires à l’armée ? La fée des rations.",
      "Pourquoi le Capitaine Crochet a-t-il participé à la Nouvelle Star ? Parce que c’est une émission de télé-crochet.",
      "Qu’est-ce qu’un livret d’instructions qui danse ? Un Manuel Valls.",
      "Qu’est-ce qu’une gousse d’ail qui est malade et fatiguée ? Un aïoli.",
      "Qu’est-ce qu’une personne de petite taille qui a une peau soyeuse ? Un naindoux.",
      "Avec quoi une fusée mange-t-elle sa soupe ? Avec une tuyère.",
      "Qu’est-ce qu’un cochon avec un pinceau ? De lard.",
      "Pourquoi Justin Bieber a-t-il une voix aussi aiguë ? Parce qu’il a joué au saute-mouton avec une licorne dans son enfance.  ",
      "Pourquoi un annuaire téléphonique présente-t-il une très grande habileté ? Car il a beaucoup d’adresse(s).",
      "Pourquoi l’Espagne n’a-t-elle pas de poils ? Car il a un Cordoue.",
      "Pourquoi ne faut-il jamais acheter un téléphone à un avion ? Pour qu’il évite de décrocher.",
      "Pourquoi un compas est-il le meilleur ami des êtres qui sont tristes ? Car il fait souvent preuve de compassion.",
      "Qu’est-ce qu’un père qui veut devenir une mère ? Un trans parent.",
      "Quel est le fruit qui suit toujours les dernières tendances ? Les dattes : elles sont branchées.",
      "Quel est le plat préféré du général de Gaulle ? Le plat de résistance.",
      "Quel est le comble de M. Sanchez ? De ne trouver nulle part où s’asseoir.",
      "Quel est le meilleur ami de la farine ? C’est l’ami Don.",
      "Quel est l’hymne des accumulateurs déchargés ? « Allons enfants de la batteri-ie, je jour de charge est arrivé… »",
      "Quel est l’arbre le plus frustré ? Le sapin : il a les boules.",
      "Quel est le jeu de cartes préféré des hamsters ? Le Ham-tarot.",
      "Pourquoi le bois est-il connu pour être silencieux ? Parce qu’il sait stère.",
      "Quel est l’avion le plus rigolo ? Le drôle.",
      "Pourquoi un palmier a-t-il de vrais potes ? Parce qu’il n’a que des amis de longue datte !",
      "Si un individu est, étymologiquement, un être indivisible, est-ce que Louis XVI est un individu ?",
      "Pourquoi un piano est-il très fort en cours ? Parce qu’il a de bonnes notes.",
      "Quel type de culture (dans l’agriculture) est la plus marrante ? La rizière.",
      "Quelle est la différence entre la peau de Ron Weasley et une feuille de papier ? Au bout d’un certain temps, la feuille de papier prend des couleurs…",
      "Comment reconnait-on une orange qui prend tout son temps ? C’est celle qui n’est pas pressée.  ",
      "Quel serait le comble pour les gens bons ? Payer les frais de porc lors de leurs achats en ligne.",
      "Quelle est la couleur la plus patiente ? Le jaune parce que Jonathan.",
      "Quel est la poupée la plus dangereuse ? La Barbie Turique. ",
      "Pourquoi les pneus sont-ils de gros délinquants en hiver ? Parce qu’ils sont enchaînés. ",
      "Tu connais le nom de la fille qui est toujours célibataire car elle fait fuir tout le monde ? Elle s’appelle Éva Cuation.",
      "Dans quelle université un copieur va-t-il ? À la fac Simile.  ",
      "Pourquoi faut-il faire de la collocation avec Napoléon ? Parce qu’il a un Bonaparte.",
      "Pourquoi Sting sait-il très bien s’épiler ? Parce qu’il a la Police. ",
      "Quelle est la lettre la plus fraîche de l’alphabet dans le Nord ? La lettre B : parce qu’il y a plein de beffrois là-bas !",
      "Pourquoi les agents du renseignement israéliens sont-ils de mauvaise humeur ? Parce qu’ils sont d’humeur Mossad.",
      "Pourquoi la Slovaquie est-elle plus riche que la Rép. Tchèque ? Parce qu’ils faisaient souvent des Tchécoslovaques.",
      "Pourquoi certains fabricants de chaussures sont-ils toujours déconnectés de la réalité ? Parce qu’ils sont à côté de leurs pompes.",
      "Qu’est-ce qu’un mauvais train ? Un train qui arrive sans crier gare.",
      "Pourquoi un sapin n’est-il jamais content en hiver ? Parce qu’on l’enguirlande.",
      "Pourquoi ne faut-il jamais prendre de boissons à la mode ? Parce que sinon, ça fait de la coca in !",
      "Pourquoi un haut-parleur attend-il un enfant ? Parce qu’il est enceinte.",
      "Pourquoi fait-il donner des carottes à Diam’s ? Pour faire des carottes râpées.",
      "Quel est le pays qui a le meilleur pouvoir d’achat ? L’Azerbaïdjan : ils achètent tout à Bakou.",
      "Quel objet est le meilleur magicien ? Le moteur : il peut faire plein de tours.",
      "Qu’est-ce milkshake ? 20 carnets de 50 chèques.",
      "Quel est le secteur le plus porteur ? Celui de la construction : ils font de nombreux murs porteurs.",
      "Que dit une lotion Carrefour à une lotion de luxe (genre une lotion Chanel) ? « Tu n’as pas la lotion de l’argent ! »",
      "Pourquoi les Tchadiens sont-ils orphelins ? Parce qu’ils n’ont pas de mers.",
      "Pourquoi ne faut-il pas regarder un film avec une aile d’avion ? Parce qu’il peut te spoiler.   ",
      "Quel est le comble pour un frigo ? D’être payé en trois fois sans frais !",
      "Pendant les attentats du 11 Septembre, pourquoi il aurait fallu filmer d’en bas ? Pour entendre les gens chanter « It’s raining men ! ».",
      "Quel est le point commun entre un bus de belges, Lady Diana et un téléphone ? Les trois ne passent pas sous un tunnel.",
      "Dans Titanic, c’est Rose qui aurait dû couler et non Jack : au moins, ça aurait été un film à l’eau de rose.",
      "Quel est le jeu préféré des croque-morts ? Le cadavre exquis.",
      "Si un gars s’immole par le feu, est-ce un one man chaud ?"];
    var nbBl = lol.length;

    var i = Math.floor(nbBl*Math.random());
    msg.reply(lol[i]+' © Bob Sleigh');
  },
};
